from server.schemas.analytics_schema import AgentDailyStatus
from server.schemas.ticket_summary_schema import TeamLeadTicketSummary,SupportTicketSummary,EmployeeTicketSummary
# from server.schemas. import TeamLeadTicketSummary
from server.models.db_model import Ticket, User, Customer, Dept
from server.dependencies import get_db,get_current_user

from fastapi import APIRouter,Depends,HTTPException
from sqlalchemy.orm import Session
from datetime import datetime,date,timedelta
from sqlalchemy import func,case,cast,Date

router = APIRouter(prefix="/analytics", tags=["Analytics"])

#shows only those tickets generated by the employee and total tickets they have till right now
@router.get("/employee/summary",response_model=EmployeeTicketSummary)
def employee_ticket_summary( db:Session = Depends(get_db),current_user : User = Depends(get_current_user)):

    if current_user.role == "employee":

        tickets = db.query(Ticket).filter(Ticket.created_by_user_id == current_user.id).all()
        return {
            "total_tickets":len(tickets),
            "tickets":[
                {
                    "id": t.id,
                    "title": t.title,
                    "status": t.status,
                    "priority":t.priority
                } for t in tickets
            ]
        }
    else:
        raise HTTPException(status_code=403,detail=["Only an employee can see"])


#shows the tickets generated by the Support Agent and count of each customer's ticket(like 1 customer  have 3 tickets it will show total tickets 3)
@router.get("/support/summary",response_model=SupportTicketSummary)
def support_ticket_summary(db:Session = Depends(get_db),current_user : User = Depends(get_current_user)):
    
    if current_user.role != "support":
        raise HTTPException(status_code=403,detail=["Only support agent can access this"])
    
    total_tickets = db.query(Ticket).filter(Ticket.assigned_agent == current_user.id).count()

    customer_count = db.query(Customer.id.label("customer_id"),
                              Customer.name.label("customer_name"),
                              func.count(Ticket.id).label("ticket_count")
                              ).join(Ticket,Ticket.customer_id == Customer.id).filter(
                                Ticket.assigned_agent == current_user.id).group_by(Customer.id).all()
    return {
        "total_tickets": total_tickets,
        "tickets_by_customer": customer_count
    }


#shows all the ticket that can be viewed by Team Lead
@router.get("/team-lead/summary",response_model=TeamLeadTicketSummary)
def team_lead_ticket_summary( db: Session = Depends(get_db), current_user : User = Depends(get_current_user)):

    if current_user.role != "team_lead":
        raise HTTPException(status_code=403,detail=["This can only be accessed by TEAM LEAD"])
    
    tickets = db.query(Ticket).filter().all()

    return{
        "total_tickets":len(tickets),
        "tickets":[
            {
                "id": t.id,
                "title": t.title,
                "status": t.status,
                "priority":t.priority,
                "assigned_agent":t.assigned_agent,
                "customer_id": t.customer_id,
                "created_at" : t.created_at
            } for t in tickets
        ]
    }

#shows weekly agent stats of how many tickets are open,closed,pending
@router.get("/weekly",response_model=list[AgentDailyStatus])
def weekly_agent_stats(db:Session = Depends(get_db),current_user: User = Depends(get_current_user)):

    if current_user.role!= "team_lead":
        raise HTTPException(status_code=403,detail=["Not the accessed user"])
    
    current_time = datetime.utcnow()
    last_week = current_time - timedelta(days=7)

    states = (
        db.query(Dept.dept_id,
                 Dept.dept_name,
                 Ticket.assigned_agent.label("agent_id"),
                 User.name.label("agent_name"),
                 cast(Ticket.created_at,Date).label("date"),
                 func.count(case((Ticket.status == "open",1))).label("opened"),
                 func.count(case((Ticket.status == "pending",1))).label("pending"),
                 func.count(case((Ticket.status == "closed",1))).label("closed"),
                 ).join(
                     User, User.id == Ticket.assigned_agent
                 ).filter(
                     Ticket.created_at >= last_week,
                     Ticket.assigned_agent.isnot(None)
                 ).group_by(
                     Ticket.assigned_agent,
                     User.name,
                     cast(Ticket.created_at, Date)
                 ).order_by(
                     cast(Ticket.created_at, Date),
                     Ticket.assigned_agent
                 ).all()
    )
    return states