from server.dependencies import get_db,get_current_user
from server.models.db_model import Ticket,User,Customer
from server.schemas.ticket_schema import TicketResponse, CreateTicket,TicketDeleteRequest,AssignTicketRequest
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from server.algo_services.round_robin import assign_next_agent
from fastapi import Depends,HTTPException,APIRouter
# from server.schemas.ticket_summary_schema import EmployeeTicketSummary, SupportTicketSummary,TeamLeadTicketSummary
from sqlalchemy.sql import func, case
from server.db_connect.ticket_state import ALLOWED_STATUS_TRANSITIONS

router = APIRouter(prefix="/tickets", tags=["Tickets"])


@router.get("/",response_model=list[TicketResponse])
async def get_ticket(db:Session=Depends(get_db),current_user : User = Depends(get_current_user)):

    if current_user.role == "employee":
        return (
            db.query(Ticket).filter(Ticket.created_by_user_id == current_user.id).all()
        )
        # raise HTTPException(status_code=403,detail="Only for the Authorized members")

    if current_user.role == "support":
        return (
            db.query(Ticket).filter(Ticket.assigned_agent == current_user.id).all()
        )
    
    #for team lead
    return db.query(Ticket).all()


#will works when an employee creates a ticket cuz it will auto assign the ticket to an agent using round robin algo
@router.post("/",response_model=TicketResponse)
async def create_ticket(
    ticket : CreateTicket, db: Session = Depends(get_db),current_user : User = Depends(get_current_user)
):
    
    if current_user.role not in ["employee","support"]:
        raise HTTPException(status_code=404,detail="Not allowed")
    
    assigned_agent_id = None
    status = "open"

    if current_user.role == "employee":
        assigned_agent_id = assign_next_agent(db)
        if assigned_agent_id:
            status = "pending"

    if current_user.role == "support" and not ticket.customer_id:
        raise HTTPException(status_code=401,detail="Customer required")
    
    new_ticket = Ticket(
        title = ticket.title,
        description = ticket.description,
        priority = ticket.priority,
        created_by_user_id = current_user.id,
        assigned_agent = assigned_agent_id, #current_user.id if current_user.role == "support" else None,
        customer_id = ticket.customer_id
    )

    db.add(new_ticket)
    db.commit()
    db.flush()
    return new_ticket



#shows only those tickets generated by the employee and total tickets they have till right now
# @router.get("/employee/summary",response_model=EmployeeTicketSummary)
# def employee_ticket_summary( db:Session = Depends(get_db),current_user : User = Depends(get_current_user)):

#     if current_user.role == "employee":

#         tickets = db.query(Ticket).filter(Ticket.created_by_user_id == current_user.id).all()
#         return {
#             "total_tickets":len(tickets),
#             "tickets":[
#                 {
#                     "id": t.id,
#                     "title": t.title,
#                     "status": t.status,
#                     "priority":t.priority
#                 } for t in tickets
#             ]
#         }
#     else:
#         raise HTTPException(status_code=403,detail=["Only an employee can see"])
    


#shows the tickets generated by the Support Agent and count of each customer's ticket(like 1 customer  have 3 tickets it will show total tickets 3)
# @router.get("/support/summary",response_model=SupportTicketSummary)
# def support_ticket_summary(db:Session = Depends(get_db),current_user : User = Depends(get_current_user)):
    
#     if current_user.role != "support":
#         raise HTTPException(status_code=403,detail=["Only support agent can access this"])
    
#     total_tickets = db.query(Ticket).filter(Ticket.assigned_agent == current_user.id).count()

#     customer_count = db.query(Customer.id.label("customer_id"),
#                               Customer.name.label("customer_name"),
#                               func.count(Ticket.id).label("ticket_count")
#                               ).join(Ticket,Ticket.customer_id == Customer.id).filter(
#                                 Ticket.assigned_agent == current_user.id).group_by(Customer.id).all()
#     return {
#         "total_tickets": total_tickets,
#         "tickets_by_customer": customer_count
#     }



#shows all the ticket that can be viewed by Team Lead
# @router.get("/team-lead/summary",response_model=TeamLeadTicketSummary)
# def team_lead_ticket_summary( db: Session = Depends(get_db), current_user : User = Depends(get_current_user)):

#     if current_user.role != "team_lead":
#         raise HTTPException(status_code=403,detail=["This can only be accessed by TEAM LEAD"])
    
#     tickets = db.query(Ticket).filter().all()

#     return{
#         "total_tickets":len(tickets),
#         "tickets":[
#             {
#                 "id": t.id,
#                 "title": t.title,
#                 "status": t.status,
#                 "priority":t.priority,
#                 "assigned_agent":t.assigned_agent,
#                 "customer_id": t.customer_id,
#                 "created_at" : t.created_at
#             } for t in tickets
#         ]
#     }



@router.patch("/{ticket_id}/status")
async def update_ticket_status(ticket_id : int,new_status : str,db: Session = Depends(get_db),current_user:User = Depends(get_current_user)):

    tickets = db.query(Ticket).filter(Ticket.id == ticket_id).first()

    if not tickets:
        raise HTTPException(status_code=404,detail=["Ticket not found"])
    
    if current_user.role not in ["support","team_lead"]:
        raise HTTPException(status_code=403,detail=["Only for authorized entity"])
    
    current_status = tickets.status

    if new_status not in ALLOWED_STATUS_TRANSITIONS[current_status]:
        raise HTTPException(status_code=400,detail=["Not allowed this kind of direct transition"])
    
    tickets.status = new_status
    db.commit()

    return {
        f"ticket status moved from {current_status} to {new_status}"
    }



# @router.get("/team-lead/weekly")
# def tl_weekly_stats(db: Session = Depends(get_db), current_user : User = Depends(get_current_user)):

#     if current_user.role != "team_lead":
#         raise HTTPException(status_code=403,detail=["Only for TEAM LEADs"])
    
#     current_time = datetime.utcnow()
#     last_week = current_time - timedelta(days=7)

#     stats = (
#         db.query(func.date(Ticket.created_at).label("date"),

#                  func.count(case((Ticket.status == "open",1))).label("opened"),
#                  func.count(case((Ticket.status == "pending",1))).label("pending"),
#                  func.count(case((Ticket.status=="closed",1))).label("closed")).filter(Ticket.created_at >= last_week)
#                  .group_by(func.date(Ticket.assigned_agent)).order_by(func.date(Ticket.created_at)).all())
    
#     return [
#         {
#             "date": row.date,
#             "opened": row.opened,
#             "pending": row.pending,
#             "closed": row.closed
#         }for row in stats
#     ]


@router.delete("/{ticket_id}")
async def delete_ticket(ticket_id : int,delete_load: TicketDeleteRequest , db:Session = Depends(get_db),current_user : User = Depends(get_current_user)):

    if current_user.role != "support":
        raise HTTPException(status_code=403,detail=["Only support agents can access this"])
    
    ticket = db.query(Ticket).filter(Ticket.id == ticket_id).first()

    if not ticket:
        raise HTTPException(status_code=404,detail=["Ticket not found"])

    if ticket.assigned_agent != current_user.id:
        raise HTTPException(status_code=403,detail=["Not your ticket"])
    
    if ticket.status == "closed":
        db.delete(ticket)
        db.commit()
        return {"message":f"Ticket deleted of Customer {Customer.name} by agent {current_user.name}"}
    
    if not delete_load.reason:
        raise HTTPException(status_code=400,detail=["deletion request for non-closed Ticket."])
    
    ticket.deletion_reason = delete_load.reason
    db.delete(ticket)
    db.commit()

    return {
        "message": f"Ticket ID {ticket.id} deleted by agent {current_user.name}",
        "reason" : delete_load.reason
    }


#unassigned tickets can only be assigned by the team_lead

@router.patch("/{ticket_id}/assign",response_model = TicketResponse)
async def assign_ticket(ticket_id : int,assign_load: AssignTicketRequest,db :Session =Depends(get_db), current_user: User = Depends(get_current_user)):

    if current_user.role!="team_lead":
        raise HTTPException(status_code = 403,detail = ["Only Team lead can assign the task"])

    ticket = db.query(Ticket).filter(Ticket.id == ticket_id).first()

    if not ticket:
        raise HTTPException(status_code = 404,detail = ["No ticket was found"])
    
    if ticket.status != "open":
        raise HTTPException(status_code = 400,detail = ["Only OPEN tickets can be assigned"])
    
    agent = db.query(User).filter(
        User.id == assign_load.agent_id,
        User.role == "support"
    ).first()

    if not agent:
        raise HTTPException(status_code = 404,detail = ["Support Agent not found"])
    
    ticket.assigned_agent = agent.id
    ticket.status = "pending"

    db.commit()
    db.refresh(ticket)

    return ticket